### ISSUE TITLE
Snapshots: "Load view" sort of odd

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#112]
I think that if you select a view from the dropdown (again, ideally a list), it should automatically load the view, perhaps asking to save if the previous one was not saved first. It is confusing to have to "Load view" after selection.

![image](https://user-images.githubusercontent.com/13998824/118709462-fd031500-b7ea-11eb-8f55-16a5feb6fb8c.png)

**Comment by manthey** [comment]
The one issue that the Load button helps with is if load a snapshot and change something, then want to reload the same snapshot.  As soon as you change something, should the current snapshot should go back to "None"?  Or do you have to navigate away and back?  Alternately, when we make this a list, if you click an item in the list, it could immediately load the snapshot and then deselect from the list.

**Comment by arjunrajlab** [comment]
Great question. So, I think the best behavior would be that if you load a snapshot and change it, the "Save" button will get enabled. If you change the name, then if you click Save, it would be like "Save As" in that it creates a new Snapshot. If you click Save without changing the name, then it just overwrites. We could also have a "Revert to saved" button that just goes back to whatever it was before without having to navigate away and back.

**Comment by arjunrajlab** [comment]
In the case of a list: yes, I think the strategy you outline is probably best, combined with my comment above… so if you click an item, it loads it immediately. If you change it without changing the name, then it puts an asterisk or something next to the list item, and enables a "Save" button to save the change. If you change the name, then it makes a new list item (with asterisk) enables "Save" to save a new Snapshot. I do also like the idea of having a "New Snapshot" button that just starts a new list item with a default name of "Snapshot date-and-time" or something like that.
