### ISSUE TITLE
Snapshots: when resaving a Snapshot, it moves current snapshot to bottom of list instead of maintaining position

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#117]
When resaving a Snapshot, it moves current snapshot to bottom of list instead of maintaining position.

![image](https://user-images.githubusercontent.com/13998824/118827195-258e1c00-b88a-11eb-9bc8-1e6e6715baf3.png)

**Comment by manthey** [comment]
Hmm...  I was considering this a feature, as they are sorted by the order changed.

**Comment by manthey** [comment]
Or maybe it should be the reverse with the most recently saved on top?

**Comment by arjunrajlab** [comment]
I think most recent on top will be a good default. Also probably nice to have the option to sort by name and date and the other fields exposed in the list view (right now, it's just the name, but date/time probably also good).

**Comment by manthey** [comment]
As of the current code, the most recent is on top.  Maybe we should close this and make an issue to add a sort option?

**Comment by arjunrajlab** [comment]
Make a new issue to add a sort option.
