### ISSUE TITLE
Adaptive scale bar coloring based on background

### ISSUE THREAD

**Issue by pburnham50** [Kitware/UPennContrast#121]
current scale bar is black and cannot be seen/read in e.g. fluorescent-only images. would be cool if it could sense overall background and have white/grey font color if the image patch it's in is dark

**Comment by manthey** [comment]
Detecting the image under the area of the scale is probably prohibitive in terms of performance if done dynamically.  We have the histograms -- maybe if the histogram is skewed dark it should be white?  Or we could just a contrasting drop shadow and stick with one color.
