### ISSUE TITLE
Performance of Z max-merge: how much does it merge at once?

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#124]
Switching to Z max-merge seems to take a while. I'm guessing it does the max-merge for all XY positions/times, and not just the one currently shown, right? If so, is it possible to switch it to doing the max-merge just for the current frame to make it a bit more performant? Could perhaps cache it to enable faster moving around after having "visited" a frame and merged it once?

**Comment by manthey** [comment]
It only merges the current view.  Internally, the server has to fetch appropriate tiles from all of the frames to merge (on small images, this is the whole frame, but on large images, this could just be a few tiles).
