### ISSUE TITLE
max-merge and multiple file datasets

### ISSUE THREAD

**Issue by manthey** [Kitware/UPennContrast#127]
max-merge works by compositing multiple frames on the server.  This currently doesn't work if the frames are across multiple source files -- the server would need to be able to handle a source specification as part of the composite step and the client would need to pass the appropriate query parameter.

This probably also affects downloading composited regions.

**Comment by arjunrajlab** [comment]
I think that's fine for now. We could revisit this later as we work through what other file types/organizations to accept.

**Comment by manthey** [comment]
This will be addressed via #182 rather than changing the client code.
