### ISSUE TITLE
Add unroll for layers

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#129]
Add an "unroll" feature for layers:
![image](https://user-images.githubusercontent.com/13998824/121904451-31d58f80-ccf7-11eb-97f7-6ba5f8158cc4.png)

**Comment by manthey** [comment]
Per channel or per layer?  If per layer, I assume each layer still retain its specified coloring, channel, offsets, etc.

**Comment by arjunrajlab** [comment]
Good question. I think per layer, so it would retain coloring, channel, offsets, etc.

**Comment by arjunrajlab** [comment]
Updated my original issue to say layer instead of channel.

**Comment by finetjul** [comment]
@zjniu can you please give it a try ?
