### ISSUE TITLE
If I click a Configuration, it takes me to the wrong configuration

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#143]
If I click the second Configuration from the top:
![image](https://user-images.githubusercontent.com/13998824/125988577-db1f3574-a080-4f57-ab24-5fa75422cb3b.png)
it takes me to the wrong Configuration:
![image](https://user-images.githubusercontent.com/13998824/125988629-cff0ac0f-4105-48b5-81ff-9675eeeb20ce.png)
(See top right, where it says "A test configuration".)

**Comment by arjunrajlab** [comment]
Bug still there.

**Comment by boucaud** [comment]
@arjunrajlab can you test this again with master ?

**Comment by arjunrajlab** [comment]
So… I just tried it again (fresh install). I'm not sure if this bug in particular is still there, because now "New configuration" and "Duplicate configuration" don't seem to work. I couldn't actually generate a new configuration with either button.
![image](https://user-images.githubusercontent.com/13998824/149173897-6dce313b-27ad-48f9-bc8c-eb376bac4ab7.png)

**Comment by arjunrajlab** [comment]
Okay, so after reloading the page, the new configurations appeared, and from there it works: I can switch between configurations. Not sure why it required a page reload, though.
