### ISSUE TITLE
Pre-computation of tile_frames of buffers

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#154]
Reminder to pre-compute the tile_frames. I think 4Kx4K texture buffers should be okay, as long as the image quality is reasonable. I'm not sure how to define "reasonable" quality, but I think it's reasonable to be able to see the little dots recognizable as little dots (if the quality is too poor, those high frequency elements seem to get reduced to amorphous blobs).

As for the ordering of the tile_frames, I feel like it would be best to follow the same scheme as before. Tile along largest dimension first, but with the special case that XY should be encoded last—for instance if dimensions are XY=10, Z = 27, T=1, then encode by Z, then T, then XY. We could have a dataset in which XY=30, Z = 15, T = 1, but we'd still want to cache XY last because I think users are less likely to expect "instant scrubbing" through XY.

**Comment by jjomier** [comment]
@manthey to test today.

**Comment by jjomier** [comment]
Should be done today

**Comment by manthey** [comment]
This was done a while ago.
