### ISSUE TITLE
Progress indicators of loading data for high performance

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#155]
Not sure exactly what the best progress indicators are, given that there are multiple levels of caching. I think that it may be worth getting the initial image up on screen as fast as possible, and while that's up, have an indicator that says "_Pre-loading tiles_" with a progress bar in the top-left of the image window.

When someone scrubs between, say, XY, where we will likely have to load a new tile, I think it would be nice to again have an indicator along with text saying "_Loading tiles_" in the top left of the image window. Also, would be nice to have a little small text saying "_loading…_" under the slider itself, just so that people can see right there that something is loading.

I don't know if the software is still doing the lengthy (2 min) loading of the full data in the background. If so, perhaps it's worth considering whether to have another progress indicator for that as well. But I don't know how performant things are with/without that option.

**Comment by arjunrajlab** [comment]
There are progress indicators, sometimes, but they seem to show up rather inconsistently.

**Comment by manthey** [comment]
This should have been addressed with #161.
