### ISSUE TITLE
Pre-computation of max-merge

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#157]
Is it possible to pre-compute Z max-merges? It's by far the most common max-merge to perform, and so having it at the ready would be really helpful.

**Comment by jjomier** [comment]
Either pre-computation or preview/caching. 
@manthey to investigate the best technical path for this.
One way could be to compute the max-merge layer as a derivative image.
estimated: 2 days

**Comment by manthey** [comment]
Added in #238.
