### ISSUE TITLE
Toggling brightfield slider resets the zoom

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#159]
If you zoom in with brightfield off, then push "1" to toggle brightfield on, it resets to fully zoomed out:
![image](https://user-images.githubusercontent.com/13998824/137488565-78a7dc07-5441-4b0a-a8e5-ed60b7365dbe.png)
![image](https://user-images.githubusercontent.com/13998824/137488603-95814b7a-9a76-4315-a088-86dda3d74333.png)

**Comment by arjunrajlab** [comment]
I think @manthey had some thoughts on the behavior earlier, but I can't find a record of it.

**Comment by manthey** [comment]
This is caused by the hot keys being captured by geojs as well as the main application.  Geojs defaults to binding the numbers to certain zoom levels.

**Comment by arjunrajlab** [comment]
Let's turn off Geojs so it doesn't capture the hotkeys, just have the app capture hotkeys in all contexts.

**Comment by arjunrajlab** [comment]
Makes sense to keep "0" for resetting rotation, especially as a demonstration.
