### ISSUE TITLE
Property name/calculation seems odd

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#164]
Seems that when you add a property, it gives you the option to name it "Intensity YFP" once you specify the layer, but that name is not reflected in the annotation list. Instead it just says "YFP".
![image](https://user-images.githubusercontent.com/13998824/144320197-cd545684-58ad-45a9-852f-5ac51221c6ca.png)
Also, minor issue but the UI for layer and property name seem to overlap when you have multiple properties.

**Comment by arjunrajlab** [comment]
Also, if you click the refresh circle thingy, it resets layer selection.

**Comment by boucaud** [comment]
Fixed in https://github.com/Kitware/UPennContrast/pull/162 (names are now set on property creation)
