### ISSUE TITLE
Bug with listing properties

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#169]
If I compute one property and list it, then compute and list another, it shifts the values to the new property (see two screenshots below):
![image](https://user-images.githubusercontent.com/13998824/146549357-d21948b3-3d36-4e78-9d96-4a70cdb430fc.png)
![image](https://user-images.githubusercontent.com/13998824/146549400-88e3340b-71ae-49ff-8fc0-69ba0f8cfaf1.png)

**Comment by boucaud** [comment]
This should be fixed with https://github.com/Kitware/UPennContrast/pull/162/commits/f68e578cdd021d77e5951773125cfa5b1993f5ce

**Comment by boucaud** [comment]
Update: not fixed quite yet

**Comment by boucaud** [comment]
This is fixed now.
