### ISSUE TITLE
Bug with Property Caching When Rerunning Calculations

### ISSUE THREAD

**Issue by zjniu** [Kitware/UPennContrast#173]
After initially running the calculations for a property, if I edit the worker Python script, recompile the Docker image, and then rerun the calculation, the displayed property values are cached and not the updated ones. Only after adding a new point does the rerunning the calculation yield the updated property values.

**Comment by zjniu** [comment]
After further testing, it may actually not be the addition of new points that resulted in the property values updating. Refreshing the page after rerunning a calculation may be the actual way of getting properties to update.

**Comment by boucaud** [comment]
This should be fixed now as well
