### ISSUE TITLE
getTilesForDataset Not Working

### ISSUE THREAD

**Issue by zjniu** [Kitware/UPennContrast#183]
When I called the getTilesForDataset command from the datasetClient I got the following error.

`HTTP error 400: GET http://localhost:8080/api/v1//item/61e38047c61900d63a2fa357/tiles
Response text: {"message": "Invalid item id (61e38047c61900d63a2fa357).", "type": "rest"}`

I had made sure that everything was properly authenticated and that the datasetId was correct.

**Comment by manthey** [comment]
The ID should be the image ID from the dataset's configuration, not the dataset's own ID.
