### ISSUE TITLE
Data upload is very slow

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#187]
For both Will and Arjun, data upload (Chrome, Mac M1 and Mac Intel) is about an order of magnitude slower than what we saw on Adrien's computer via Zoom.

**Comment by finetjul** [comment]
On 2022/07/08: @finetjul and @luciemac will try to reproduce

**Comment by finetjul** [comment]
@manthey is waiting for a mac machine

**Comment by finetjul** [comment]
The issue is only when the front-end is a Mac (no matter the backend)

**Comment by manthey** [comment]
Closing this as we seem to have resolved it for now.

**Comment by finetjul** [comment]
@manthey for future referencing, can you please explain how the issue was resolved

**Comment by finetjul** [comment]
It seems to be a fact that docker on Mac is slow.
There are some options ([example](https://accesto.com/blog/docker-on-mac-how-to-speed-it-up/))to speed-it up, but the best is simply to use Linux on production.
