### ISSUE TITLE
Reset to saved doesn't always work

### ISSUE THREAD

**Issue by manthey** [Kitware/UPennContrast#19]
I have two layers.  The primary Z-Value is set to 1 on a three z-value data set.  On the second layer, I shift to Z-Slice Offset 1, set a range, and save it.  I then switched to Z-Slice Offset 2; the histogram shows values from 1 to 1.  When I switch back to Z-Slice Offset 1, the histogram max and min are both clamped to the low value.  I expected "reset to saved" to return to the values I saved, but it doesn't.

**Comment by sgratzl** [comment]
>  When I switch back to Z-Slice Offset 1, the histogram max and min are both clamped to the low value. I expected "reset to saved" to return to the values I saved, but it doesn't.

so far when you change the channel, z, or time slice, ... all the contrast values (max, min, saved max, saved min) will be clamped to the current values to avoid any invalid values for the current setting.

**Comment by manthey** [comment]
Right.  But when I switch back to a z slice where I had saved values and click "reset to saved", I expected the saved values to be applied (and then clamped appropriately if needed).
