### ISSUE TITLE
Docker Image Not Recognized

### ISSUE THREAD

**Issue by zjniu** [Kitware/UPennContrast#206]
Currently boucaud/spotfinding and boucaud/sample_intensity_worker are the only two docker image names recognized. If a worker was built with a different name, they do not show up in the list in the interface. For example, if a Docker image is named boucaud/spotfinding2, it does not show up when creating an automatic annotation tool.

**Comment by zjniu** [comment]
I believe this issue is now fixed with c2f2e7e0fe8b83d3b59293116b876420502b025b, but I am a bit confused on why the code has this line:
`labelFilter = lambda image : image.labels.get('isUPennContrastWorker', False) and len(image.tags)`
Why is it False instead of True?

**Comment by boucaud** [comment]
> I believe this issue is now fixed with [c2f2e7e](https://github.com/Kitware/UPennContrast/commit/c2f2e7e0fe8b83d3b59293116b876420502b025b), but I am a bit confused on why the code has this line: `labelFilter = lambda image : image.labels.get('isUPennContrastWorker', False) and len(image.tags)` Why is it False instead of True?

False is the default value returned if 'isUPennContrastWorker' is not present in the labels dictionary. If it's not present, we don't want to use the image.
