### ISSUE TITLE
Annotation selection tools not working.

### ISSUE THREAD

**Issue by zjniu** [Kitware/UPennContrast#230]
Neither the select or lasso tools are working currently on the main branch.

**Comment by luciemac** [comment]
Actually, they are not yet implemented.
You should have a warning in your console saying that ["select tools are not supported yet"](https://github.com/Kitware/UPennContrast/blob/master/src/components/AnnotationViewer.vue#L641). Do you confirm?

**Comment by luciemac** [comment]
@zjniu Can we close this one?

**Comment by zjniu** [comment]
Yep! Everything is worked as intended.
