### ISSUE TITLE
Channel toggle very buggy.

### ISSUE THREAD

**Issue by zjniu** [Kitware/UPennContrast#236]
Toggling channels on or off is currently very buggy. There are many cases when toggling off or on a channel has no effect. An example of how to reproduce such an issue is the following. Suppose we have channels A and B.

1. First turn off all channels.
2. Turn on channel A.
3. Turn on channel B.
4. Turn off channel B.
5. Turn off channel A.

Now, if we try to turn on channel A, nothing happens. Note that this is only one example and there are other ways to trigger this behavior.

**Comment by arjunrajlab** [comment]
I think this mostly works now, according to @zjniu. Apparently if you toggle really fast it can still be an issue, but I think it's fine for now.
