### ISSUE TITLE
Properties not calculated for all annotations.

### ISSUE THREAD

**Issue by zjniu** [Kitware/UPennContrast#237]
A lab member recently tried out the software on a large dataset and the properties are only calculated up to frame 15. Is there currently a limit?

**Comment by finetjul** [comment]
@zjniu Can you please provide the workflow to reproduce

**Comment by arjunrajlab** [comment]
@zjniu Ping :)

**Comment by arjunrajlab** [comment]
@zjniu Let's either reproduce or close.
