### ISSUE TITLE
Toggle selection

### ISSUE THREAD

**Issue by finetjul** [Kitware/UPennContrast#240]
On 2022/07/01, @arjunrajlab suggested to: 
 - on a new selection, toggle the current selection with the new selection. e.g. if `currentSelection={A, B, C}` and `newSelection={B, D, E}`, then new `currentSelection={A, C, D, E}`.

**Comment by finetjul** [comment]
On 2022/07/06, @luciemac suggested to add a "selection mode" button to control the behavior of the new selection:
 - NEW: the new selection clears the previous selection
 - ADD: the new selection is added to the previous selection
 - SUBSTRACT: the new selection is removed from the previous selection

**Comment by luciemac** [comment]
@finetjul guess we can close this issue?

**Comment by finetjul** [comment]
Yes #242 has implemented it, thanks.
