### ISSUE TITLE
Define application wide keyboard shortcuts

### ISSUE THREAD

**Issue by finetjul** [Kitware/UPennContrast#247]
Some keyboard shortcuts already exist:
 - arrow keys: pan the view by 1px
 - shift + arrow key: pan by 50% of the screen size
 - control + arrow key: pan by 10% of the screen size

**Comment by arjunrajlab** [comment]
Not sure if we can do "combo" hotkeys, like EMACS: e.g. "x" + "+" or something like that. But if we can, here are some hotkeys to put in. 
- Annotations on/off [a]
- XY slider (Can we do “x”+”=” and “x”+”-”?)
- Z slider (Can we do “z”+”=” and “z”+”-”?)
- T slider (Can we do “t”+”=” and “t”+”-”?)
- Show all annotation notes/tooltips [A]
- Z max-merge [“z”+”m”]

**Comment by arjunrajlab** [comment]
Also to note: we would like to have hotkeys assignable for the tools that users create.

**Comment by finetjul** [comment]
By default, "combo" hotkeys work for "shift", "ctrl" and "alt".
A mechanism to support more "combo" hotkeys could be added though.

**Comment by arjunrajlab** [comment]
Okay, so let's do the following:

Annotations on/off [a]
XY slider ("w" to left, "r" to right)
Z slider ("d" for down, "e" for up)
T slider (“s” for previous time, “f” for next time)
Show all annotation notes/tooltips [A]
Z max-merge [“z”]
