### ISSUE TITLE
Connection view not turning off when switching frames

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#253]
Connection view not turning off when switching frames

**Comment by luciemac** [comment]
@arjunrajlab What do you mean by "connection view"?

**Comment by arjunrajlab** [comment]
I'm not exactly sure. It's a comment from someone in lab. I think it means showing the connections. I think we can leave this comment until I confirm exactly what the problem is.

**Comment by arjunrajlab** [comment]
From Will: if you have connections between annotations, they are shown by a black line. When you switch to a different frame, those black lines are still there and don't disappear until you refresh the page.
