### ISSUE TITLE
Import and export of annotations

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#255]
Handy feature would be the import and export of annotations and their associated properties. We are thinking the annotations could be basically serialized as JSON and exported and imported in that way. The properties would be the ones currently displayed in the list on the annotation browser. UI would be buttons at the bottom of the annotation browser area.

**Comment by finetjul** [comment]
Additionally, add a migration script in Girder.
To do that:
 - tell @arjunrajlab how to dump the mongodb db and send it to you
