### ISSUE TITLE
Detect multi-page TIFF

### ISSUE THREAD

**Issue by finetjul** [Kitware/UPennContrast#259]
See #229 + data linked [here](https://github.com/Kitware/UPennContrast/issues/229#issuecomment-1204502271)

**Comment by manthey** [comment]
These files are being read by the tifffile tile source and are listing an axis of "I", which isn't one of Z, T, C, P (or XY).

**Comment by arjunrajlab** [comment]
Oh, I see. At least it is detecting an axis. Perhaps we just allow that axis to be specified by the user (default is Z).

**Comment by manthey** [comment]
See https://github.com/girder/large_image/pull/957.

Ultimately, we need to do something extra when a file doesn't have its internal frames labelled with an appropriate axes.

The sample files are read with the tifffile source and report that they have 6 frames, but there is no indication of the axes (e.g., are they T, Z, XY, etc).  The referenced PR allows this to be specified in the multi source's yaml/json file.  For a given source, you can add `framesAsAxes: {<axis1>: <stride1>, <axis2>: <stride2>, ...}`.  For this case, for instance, this might be `framesAsAxes: {z: 1}` to indicate that the frames are the z axis.  

We could do fancier things where an image with unlabelled axes contains two things (e.g., channel and z-stack), then that `framesAsAxes` would specify a stride for each of those axes.

@luciemac Once the associated large_image PR is merged, we'll need to add the appropriate `frameAsAxes` to the multi-source's file IF the source image doesn't have at least one of `IndexC`, `IndexT`, `IndexZ`, `IndexXY`.
