### ISSUE TITLE
Turning on and off annotations is slow.

### ISSUE THREAD

**Issue by zjniu** [Kitware/UPennContrast#261]
When there is a high number of annotations, turning on and off annotations takes a long time. See https://github.com/Kitware/UPennContrast/issues/228#issuecomment-1206866452 for a worked example for recreating.

**Comment by finetjul** [comment]
Some ideas discussed so far:
 - reproduce the issue
 - identify the reason why it is slow/crash (@manthey said geo.js should handle hundred thousands annotations)
 - potentially replace polygons with centroids for display when zooming out
 - do not display annotations when zooming out when the number of annotations is very large
 - create a heatmap when zooming out

**Comment by arjunrajlab** [comment]
Further update: appears that turning annotations ON is relatively fast, but turning off seems to take a long time.

**Comment by bruyeret-kitware** [comment]
I did a small bug fix on master to speed up annotation turn off, do you see a change?

**Comment by arjunrajlab** [comment]
I think that worked! Thank you!
