### ISSUE TITLE
Annotation tool creation UI streamlining

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#303]
Thoughts for UI for streamlining the annotation tool creation:

https://www.figma.com/file/pQthSFEYk61A1Qq6HCxbCT/Annotation-creation-UI%2FUX?node-id=0%3A1

**Comment by arjunrajlab** [comment]
I just updated the Figma slightly, let me know if you have any questions @bruyeret!

**Comment by arjunrajlab** [comment]
For the "Advanced" options, I think that it would be better to have a dropdown instead of a checkbox. Like, one of these:

<img width="47" alt="image" src="https://user-images.githubusercontent.com/13998824/201667659-d0538e9a-e492-476e-89c3-1894932c8a65.png">

Also, I think even if we cannot do the two list thing, the current UI is not very discoverable or intuitive. Let me think what might be easiest to implement but still discoverable.

**Comment by arjunrajlab** [comment]
Also, here, it should show the actual job-date tag next to the checkbox so that the user sees what the tag will be:
<img width="483" alt="image" src="https://user-images.githubusercontent.com/13998824/201674036-54ffbbc4-7889-44c9-a336-852a2b54cbd7.png">

**Comment by bruyeret** [comment]
The UI is defined in a JSON file, and in order to add some logic to the UI (add and format current date), we have to create special UI elements (like the "Annotation Configuration" or the "Connect to nearest annotation with tag").
It can be done but it will take a lot more time than adding an example tag like: `Add job date tag (e.g. "my-image job 1985-10-26 21:00:00 UTC-5")`
What do you prefer?

**Comment by arjunrajlab** [comment]
Ah, okay, I see. Let's just put in the example tag then. :) More UI feedback in a bit later today, sorry, baby has me busy :).

**Comment by bruyeret** [comment]
Ok that's done!
Congratulations on the baby! Don't worry for the UI feedback, I still have issues to work on :D

**Comment by arjunrajlab** [comment]
OK, here's my UI feedback:
https://www.figma.com/file/pQthSFEYk61A1Qq6HCxbCT/Annotation-creation-UI%2FUX?node-id=0%3A1
<img width="288" alt="image" src="https://user-images.githubusercontent.com/13998824/202412721-ae19aed8-ec5f-4ca8-95ad-221a50696243.png">

I think this significantly streamlines the UI and is more what I was envisioning. Let me know if you have questions!
