### ISSUE TITLE
Connections Not Displaying

### ISSUE THREAD

**Issue by zjniu** [Kitware/UPennContrast#304]
Connect to nearest functionality on manual annotations is currently broken. Either no connections are being made, or they are not displayed properly.

**Comment by arjunrajlab** [comment]
Can confirm that this is an issue, see Slack for screenshots. I wonder if @bruyeret maybe it's on the back end and needs to pull the latest girder/large_image docker images? We have found that we need to run docker with --no-cache a couple times to get it to fully update.
