### ISSUE TITLE
UI request for Z-max merge and channel on off switches

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#305]
Rather than have a label under the switch for every single channel, perhaps we can just show the labels once at the top to label for all channels at once? (Great idea from @zjniu!)

<img width="217" alt="image" src="https://user-images.githubusercontent.com/13998824/198895590-0ad83b93-6c2f-4607-a570-32d6ff7e43f0.png">

**Comment by bruyeret** [comment]
I didn't find a way to align the labels at the very top but I can put the labels only for the first row
What do you think about this?

![image](https://user-images.githubusercontent.com/90781029/198980122-fc6dc3bd-d0c2-486e-8c36-0396017e7e79.png)

**Comment by arjunrajlab** [comment]
I think that's fine for now! Thanks!
