### ISSUE TITLE
File name parser for data import

### ISSUE THREAD

**Issue by pburnham50** [Kitware/UPennContrast#32]
Create an "import wizard" that would read a filename, assign dimensions based on commonly used delimiters (e.g. "t##" would be timepoint ##). 

We have illustrated the motivation and an example in more detail in the following google doc:

https://docs.google.com/document/d/1osgrX3B_K3JSZdm5Ejg7kgX6H-VQRZmDZfvKiYxKWPk/edit?usp=sharing

**Comment by manthey** [comment]
This has been implemented.
