### ISSUE TITLE
Refactor UI for property computation

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#328]
As discussed on Dec 2, 2022, should refactor the UI for property computation to streamline and make more intuitive. Here's the Figma with the basic ideas, subject to creative license:
[FIGMA](https://www.figma.com/file/YDwgvMsMWyp2rQxaNfZ3sB/Property-calculation-UI-ideas?node-id=0%3A1&t=b5CY43gi905Ncnmk-0)

First refactor panels:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/13998824/205329065-ee63c490-70c6-496f-956d-fff770b3c809.png">

The "Analyze" panel should be some combination of a dialog and a list. At the top, there is a (dynamic) dialog for creating properties, and below there is a list of properties that the user has already added.

Dialog part:
<img width="754" alt="image" src="https://user-images.githubusercontent.com/13998824/205329329-cd9cac20-7fb4-4b03-b6eb-43a3aa7975da.png">

List part:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/13998824/205329384-8b4de783-7330-4658-8af2-bdc9089cc17b.png">

It would be nice to get some visual feedback on what got computed after you click "Compute", but not sure how hard that is to do, so it's lower priority for now. We could either refer back to the annotation list, or provide visual feedback like with tooltips.

**Comment by arjunrajlab** [comment]
Oh also, right now, properties seem to go across all datasets. It would be good to have them specific to particular datasets.

Also: need a name field that allows you to edit the default. 

Also: need a way to delete them.

**Comment by zjniu** [comment]
Some information that may be helpful:
Currently available images for both property and annotation workers are currently being obtained by checking if the image label isUPennContrastWorker=True: https://github.com/Kitware/UPennContrast/blob/3b5123ed34a6fb7406fcd8d610393bd1cc8a882f/devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/workerInterfaces.py#L47.

**Comment by arjunrajlab** [comment]
Here's the set of 4 property workers we could use for testing:
https://github.com/arjunrajlaboratory/ImageAnalysisProject/tree/master/workers/properties/blobs
@zjniu It might be nice to also include a property worker that works on points for testing purposes.

**Comment by arjunrajlab** [comment]
Cool so that makes a total of 5 workers. @bruyeret let us know if that is a good number. Can shorten or expand list as needed.

**Comment by arjunrajlab** [comment]
@bruyeret Actually after talking with Will today, I think it is probably better for workers to be associated with a configuration rather than the dataset. So a single dataset could in principle have multiple configurations, each of which would have its own set of property workers. Let me know if that makes sense, could be thinking about it wrong, but that seems most logical to me.

**Comment by bruyeret** [comment]
It makes perfect sense, what should I do with the properties which have already been created without a dataset/configuration?
Display them on all datasets/configuration or never display them?

I'm really close to being done with the UI, I still have to:
- create a button to delete properties
- fix the workers not emitting an event when they are done

I also fixed a performance issue which may have fixed @zjniu's problem with old datasets and many other small bugs

**Comment by arjunrajlab** [comment]
Cool, we will test it! For existing properties… I think we should probably not display them. However, this raises a question of which properties to show. I guess properties are associated with annotations, right? So then do you show all properties calculated for an annotation, even after the property calculator has been removed? I guess the answer is yes, but then the UI is a little more complex I guess… we can discuss on Friday.

**Comment by zjniu** [comment]
@bruyeret I just pulled in the new updates. I don't believe that the performance issue on old datasets is totally fixed. It is much better; there is now only a 2-3 second freeze as opposed to around 10 seconds from before. However, there is still something preventing the whole experience from being completely smooth. I am going to reproduce this issue soon and provide you with a zipped file containing the assetstore, db, and logs so you could play around with it on your end.

**Comment by arjunrajlab** [comment]
For newly uploaded data, there is no slowness.

**Comment by bruyeret** [comment]
Ok let's discuss what we do about property workers tomorrow
@zjniu You explained how to reproduce in #329, I think it will be enough but if I can't reproduce, we can tru the zipped file technique
