### ISSUE TITLE
Collections UI: chip click

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#377]
When I click the “Config” chip, it takes me to the dataset, but I would have expected that clicking on the chip would take me to the configuration page.

<img width="708" alt="image" src="https://user-images.githubusercontent.com/13998824/236360160-5d73eb93-44ce-471f-a273-7ae360ef63e8.png">

**Comment by bruyeret** [comment]
Would something like this be better:
- clicking a chip brings you to the info page for the clicked configuration / dataset
- clicking the eye icon brings you to the view for the combination configuration + dataset

![image](https://user-images.githubusercontent.com/90781029/236406817-5d573a07-51df-462d-a9c6-7bbe555a2f41.png)

**Comment by arjunrajlab** [comment]
I think the eye is sort of confusing. Probably for most users they want the dataset or the configuration. It's not particularly clear what the eye does in this case.
