### ISSUE TITLE
Collections UI: reconfigure UI once data uploaded

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#379]
I find this screen a bit confusing:

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/13998824/236362393-63de2d30-abfa-4a73-8eae-6a154cf851f9.png">

I think it might make more sense like this:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/13998824/236362902-0477c488-6a5f-46ab-829d-044ccaa93379.png">

That also gets rid of the extra step of creating and naming a new view. If you click "View Dataset" it takes you straight to viewing the dataset.

**Comment by bruyeret** [comment]
Should I remove the "Create new configuration" button?
The problem with a default configuration is the location of the default configuration: where should the default configuration be?

**Comment by bruyeret** [comment]
A default configuration could also be useless if the user wants to use an existing configuration
Maybe a solution is to add a new page after updating a dataset asking if the user wants to:
- create a default configuration and where to put it
- use an existing configuration
- duplicate an existing configuration and where to put the duplicate

**Comment by arjunrajlab** [comment]
Yes, I would replace the "Create New Configuration…" button with the "View Dataset" button. I think we could just put the file in the same directory as the Dataset.

If a user wants to use an existing configuration, then they would still just click the "Add to existing collection…" button, which would work exactly like the current button (bringing up the selection interface).

**Comment by bruyeret** [comment]
This is what I have done and pushed on fix-collections branch
What do you think?
The green button with text field only show up when there is no configuration associated with the dataset

![image](https://user-images.githubusercontent.com/90781029/236504749-bde52a7b-d164-46c9-9353-0a2fc5d660d0.png)

**Comment by arjunrajlab** [comment]
That looks good @bruyeret! One minor thing: I think the button should say "View dataset" to avoid confusion. Also, the name of the configuration should be made from the Dataset Name:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/13998824/236523555-dd734367-d530-4314-9361-cc12550b567a.png">

**Comment by bruyeret** [comment]
Thanks, this is fixed!
