### ISSUE TITLE
General Data Upload and Configure Procedure

### ISSUE THREAD

**Issue by pburnham50** [Kitware/UPennContrast#39]
We describe what we think would be a very UI friendly data import procedure - as well as some issues/bugs we have encountered, at the following google Doc https://docs.google.com/document/d/1FjB_HgSd6LiWxuYta0jRJVu5ZkNUVdl3e1xPNAgL4Ms/edit?usp=sharing .

**Comment by manthey** [comment]
This was mostly implemented.  We should make new issues as desired for anything remaining.
