### ISSUE TITLE
Can we make the popup window stand out a little more?

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#416]
The popout window is good, but tends to blend into the overall background, which has led to some inadvertent clicks on "unroll". Can we make it stand out a bit more, perhaps with a drop shadow or outline or something?

<img width="815" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/41da7075-df28-478d-bb14-2c8f377a261c">

**Comment by bruyeret** [comment]
Is it better with a border?

![image](https://github.com/Kitware/UPennContrast/assets/90781029/fa9c9836-42f6-4a30-9f66-3a63f2eaa092)
