### ISSUE TITLE
Exporting large number of annotations to CSV crashes entire UI

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#419]
We have found that when exporting >100K annotations to CSV, the operation works and produced the CSV, but then the entire UI shuts down (like, the terminal running the server actually quits). I saw in a previous issue that perhaps this is related to the fact that the CSV is generated by the front end, but not sure.

**Comment by bruyeret** [comment]
Generation of the CSV by the frontend should not be a problem, as it is not really different than fetching the annotations
I made [a PR](https://github.com/Kitware/UPennContrast/pull/430) which may solve the issue and other scaling related issues
Does it work for you?

**Comment by arjunrajlab** [comment]
Can you rebase from master?
I will test ASAP! It is a very weird problem. The CSV actually gets generated and downloaded, it was more that AFTER generating the CSV, the UI crashed. But let me ask someone to test it.

**Comment by bruyeret** [comment]
The branch is up to date with master, do you want to merge it now?
This is weird, I tried with 400k annotations and nothing crashed when exporting to CSV
I just had an issue when opening the view but it should be solved by the PR

**Comment by arjunrajlab** [comment]
Cool, yeah who knows. I would just merge! We'll test and go from there if the problem appears again.
