### ISSUE TITLE
File parsing with a single multi-page TIFF doesn't allow for changing the variable

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#448]
Take for instance loading a single multi-page TIFF. Here is an example:

MS_1.tiff

https://www.dropbox.com/scl/fi/1ght7mp7582vn97w6ppew/MS2_1.tif?dl=0&rlkey=fi4944g03hum38ioe7m2x7av6

It's a time series, but when it loads, it interprets it as a z series. Which is the right default behavior, but there is no option to "clear" the variable and reassign it to something else, like T.

<img width="1179" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/11eea2e2-3df7-4aa9-a8d3-dc2ef40e388f">

**Comment by bruyeret** [comment]
By default, variables that are found from the file metadata (Source column) can't be cleared
For example: `normmedia_8well_col2_livecellgfp.nd2` has all of its variables from the file metadata, and the variables can't be cleared
Should it be possible to clear variables when the source is "file"?

**Comment by arjunrajlab** [comment]
So… for ND2 files, we know from the embedded metadata what the variables should be, and that should not be changeable. However, for a multi-page TIFF, we don't know ahead what variable it should be (in this case, it should be time, but instead it was interpreted as Z. So I guess for file types in which we don't have explicit metadata, we should be able to clear variables when the source is file.
