### ISSUE TITLE
Add a way to remove the underlying data, but keep all the annotations and rest of the dataset

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#477]
As our server gets full, it would be nice to be able to remove the underlying data but keep the rest of the dataset, including annotations and configurations and so forth. Then, if someone needs to look again later, they can just reupload the data into the dataset. Not sure exactly how to do this, but it seems that Girder has the appropriate functionality.

**Comment by arjunrajlab** [comment]
After talking with @bruyeret and @finetjul, I think I can try to more completely specify a potential solution. The idea would be to have two (or more) asset stores. One could be, for example, some cheap "cold" AWS storage, and another could be the local SSD. When you upload a dataset, there is a default asset store (but could also add the option to choose between asset stores). Once the dataset is in there, then we should have the option to move it to a different asset store. I think having a dropdown here in the "Dataset" panel would be good.

![Image](https://github.com/Kitware/UPennContrast/assets/13998824/d16ea893-33d1-430f-afd7-16f2cee57e83)

I think it's also important to have an "Are you sure?" dialog, since moving files in and out of AWS probably can cost some money. Similarly, I think the "View" button should maybe have an "Are you sure? Reading this file requires loading from AWS." dialog if it is on the AWS cold asset store, just so that people are aware.

I am assuming that Girder can relatively easily and transparently manage moving data between asset stores, but if that's hard, let me know.

**Comment by manthey** [comment]
There are endpoints for moving any file to a different assetstore.  Further, with the User and Collection Quotas plugin, you can have specific users and collections default to specific assetstores.  In Girder, there is a PUT file/{id}/move endpoint to move to another assetstore, and a PUT folder/{id}/move endpoint for folders (though that might be added by one of the other plugins).  Because we save thumbnails, cache histograms, tile frames, etc, to fully move all assets related to a data set might require some additional work (though except for the max-merge files and tile frames, these should be comparatively small).

**Comment by manthey** [comment]
Because we are using a plugin-specific annotation model, we should have a cron job to backup the mongo database.  See https://github.com/DigitalSlideArchive/digital_slide_archive/blob/a9cda65a91d464a9d0d26d9015b38194b19bb11f/devops/dsa/README.rst#database-backup

**Comment by arjunrajlab** [comment]
What would be involved if we wanted to copy a user from one girder server to another?

**Comment by manthey** [comment]
You can copy the user account and all the data using the girder api.  There is a somewhat hacky utility tool for this but it doesn't know about plugin-specific models, such as annotations (and doesn't currently copy over permissions).  The copied user would need to have the password reset by an admin.

Alternately, you could copy the relevant portions of the database.  I think the password would still need to be reset by an admin, as the salt used for passwords is installation specific, and this would require ensuring walking all of the relevant collections.

**Comment by bruyeret** [comment]
I don't see the `move` endpoints to change the assetstore of a folder @manthey 
So I think it is in a plugin that we don't use yet in NimbusImage
What is the name of this plugin and how can I add it to Girder?

**Comment by manthey** [comment]
The plugin is https://github.com/DigitalSlideArchive/import-tracker.  It can be added by pip installing from the repo (e.g., `pip install git+https://github.com/DigitalSlideArchive/import-tracker.git`

**Comment by bruyeret** [comment]
Thanks! Now I have the endpoint in the `/api/v1` page but it only works with an administrator user
I also have the issue with the `GET /assetstore` to find the existing assetstores

**Comment by bruyeret** [comment]
I think the issue mentionned by @arjunrajlab [here](https://github.com/Kitware/UPennContrast/pull/741#issuecomment-2212540745) would fit with this issue
What do you think about it @manthey?

**Comment by bruyeret** [comment]
Oh yes, that would be very helpful, because it would avoid having to dive into a new code base!
So I will be able to just use something like this?
```python
from import_tracker.utils import moveFolder
```

**Comment by manthey** [comment]
> Oh yes, that would be very helpful, because it would avoid having to dive into a new code base! So I will be able to just use something like this?
> 
> ```python
> from import_tracker.utils import moveFolder
> ```

Refactored in https://github.com/DigitalSlideArchive/import-tracker/pull/39.

**Comment by bruyeret** [comment]
Thanks! I subscribed to this PR!
