### ISSUE TITLE
Interface becomes sluggish with high number of polygon annotations

### ISSUE THREAD

**Issue by zjniu** [Kitware/UPennContrast#481]
We recently did a test by adding 50,000 polygon annotations displayed all at once on a huge stitched image. The annotations still loaded, and if zoomed in, the interface is still usable. However, it felt noticeably sluggish.
![56AD47CF-FEDF-46C3-9761-F7EA1A49D4EF](https://github.com/Kitware/UPennContrast/assets/87096829/8052c103-f98e-4c41-929a-4b086fa6a41f)
![CBD9397C-E9A5-4EF0-AA3C-A0D3C3C54502](https://github.com/Kitware/UPennContrast/assets/87096829/21d2ec29-d882-46ff-8744-ca0925e657be)

**Comment by arjunrajlab** [comment]
Update: this seems to mostly occur when the underlying data is a very large image. For a smaller image with the same number of polygons, it seems to be okay. It could also be the polygon complexity, not sure.
