### ISSUE TITLE
"Name" column not exported in CSV

### ISSUE THREAD

**Issue by zjniu** [Kitware/UPennContrast#488]
The "Name" column in the annotation browser is not being exported in the CSV.

![image](https://github.com/Kitware/UPennContrast/assets/87096829/224f391a-8878-4842-a628-d3f2efb9d567)

![image](https://github.com/Kitware/UPennContrast/assets/87096829/70d611f0-ee3c-48ab-925f-dcd93cfb469e)

**Comment by arjunrajlab** [comment]
Already have this issue: https://github.com/Kitware/UPennContrast/issues/471

**Comment by zjniu** [comment]
I believe these issues are different. The name column I'm describing allows the user to input comments about each annotation.

**Comment by arjunrajlab** [comment]
Oooh sorry!
