### ISSUE TITLE
TIFF stack correctly being parsed but axis assignment fails.

### ISSUE THREAD

**Issue by zjniu** [Kitware/UPennContrast#491]
I created a TIFF stack using the `tifffile` package and specifying the axis order using `tifffile.imwrite('image.tif', image, metadata={'axes': 'CYX'})`. [Here](https://www.dropbox.com/scl/fi/9ijpjn08h9175w0new4d2/2023_05_23_pw020_ctrl_well1.tif?dl=0&rlkey=bhx3grmyudbl9722et6escutp) is one such TIFF to this issue, which has a total of 4 channels. While the parser successfully detects the channels, as shown below, it fails to assign the axes properly. The size of each axis is displayed as a question mark.

![image](https://github.com/Kitware/UPennContrast/assets/87096829/77ff75ef-4a2d-4637-9d58-f53f0bc8c712)

![image](https://github.com/Kitware/UPennContrast/assets/87096829/3642d025-6a54-4333-9c27-9ee525e782f1)

**Comment by manthey** [comment]
This file contains erroneous information.  It has some metadata from tifffile that says it is `{"axes": "ZTCYX", "shape": [1, 1, 4, 1000, 1000]}`, but it appears to be written as `"shape": [1, 1, 1000, 1000, 4]`.  Moreover, the last value is four BANDS (also called samples), not CHANNELS.  tifffile won't read the pixels in the file (even if it was used to write it).  

Probably if it had been written `tifffile.imwrite('image.tif', image, metadata={'axes': 'YXC'})` it would have been fine.

**Comment by manthey** [comment]
See https://github.com/girder/large_image/pull/1273 for a change that hardens against this sort of badly written file.

**Comment by zjniu** [comment]
@manthey The command that you suggested didn't work. The UI thought that the image had 1000 channels.

**Comment by manthey** [comment]
Can you send a code snippet of what you are doing with tifffile to make the image stack (with numpy zero arrays, for instance)?  I find it odd that you have to specify axes manually and then it can't read them back.  It makes me think that tifffile is inconsistent or the api is different than you expect.

**Comment by zjniu** [comment]
This is akin to the original code I had written.

```python
import numpy as np
import tifffile

image = np.zeros((1, 1, 4, 1000, 1000))
tifffile.imwrite('test.tif', image, metadata={'axes': 'ZTCYX'})
```

**Comment by manthey** [comment]
Hmm... When I use tifffile to write things out, they end up the expected way (that is, my dimensions and axes correspond -- as you note, my example would have produced 1000 channels).  I can't make a tiff file that is broken in the manner that you shared.  Your tiff file had some interesting properties (tifftools dump <file> is shown below), such as white points and chromacities.  Are you using some other library to facilitate writing these?  Even overriding the photometric and planar arrangement still gets me good files (not like yours).

```
-- 2023_05_23_pw020_ctrl_well1.tif --
Header: 0x4949 <little-endian> <ClassicTIFF>
Directory 0: offset 8000008 (0x7a1208)
  ImageWidth 256 (0x100) SHORT: 1000
  ImageLength 257 (0x101) SHORT: 1000
  BitsPerSample 258 (0x102) SHORT: <4> 16 16 16 16
  Compression 259 (0x103) SHORT: 1 (None 1 (0x1))
  Photometric 262 (0x106) SHORT: 2 (RGB 2 (0x2))
  FillOrder 266 (0x10A) SHORT: 1 (MSBToLSB 1 (0x1))
  ImageDescription 270 (0x10E) ASCII: {"axes": "ZTCYX", "shape": [1, 1, 4, 1000, 1000]}
  StripOffsets 273 (0x111) LONG: <8> 8 1024008 2048008 3072008 4096008 5120008 6144008 7168008
  Orientation 274 (0x112) SHORT: 1 (TopLeft 1 (0x1))
  SamplesPerPixel 277 (0x115) SHORT: 4
  RowsPerStrip 278 (0x116) SHORT: 128
  StripByteCounts 279 (0x117) LONG: <8> 1024000 1024000 1024000 1024000 1024000 1024000 1024000 832000
  XResolution 282 (0x11A) RATIONAL: 1 1 (1)
  YResolution 283 (0x11B) RATIONAL: 1 1 (1)
  PlanarConfig 284 (0x11C) SHORT: 1 (Chunky 1 (0x1))
  Xposition 286 (0x11E) RATIONAL: 0 1 (0)
  Yposition 287 (0x11F) RATIONAL: 0 1 (0)
  ResolutionUnit 296 (0x128) SHORT: 1 (None 1 (0x1))
  PageNumber 297 (0x129) SHORT: <2> 0 1
  WhitePoint 318 (0x13E) RATIONAL: <2> 10492471 33554432 (0.3127) 689963 2097152 (0.329)
  PrimaryChromaticities 319 (0x13F) RATIONAL: <6> 5368709 8388608 (0.63999999) 11072963 33554432 (0.33000001) 5033165 16777216 (0.30000001) 5033165 8388608 (0.60000002) 5033165 33554432 (0.15000001) 16106127 268435456 (0.059999999)
  ExtraSamples 338 (0x152) SHORT: 2 (UnassociatedAlpha 2 (0x2))

```

**Comment by zjniu** [comment]
Nope, I'm running the code exactly as is using tifffile 2023.8.12.

**Comment by zjniu** [comment]
Could you provide me an example TIFF from your end that is considered a "good file"?

**Comment by cgohlke** [comment]
> `tifffile.imwrite('test.tif', image, metadata={'axes': 'ZTCYX'})`

Two issues:

- The code writes a TIFF with the extra metadata stored in tifffile's format. I don't think any other software supports that metadata format. Better write a standard format like OME-TIFF if possible, e.g., `tifffile.imwrite('test.ome.tif', image, metadata={'axes': 'ZTCYX'})`.
- The `metadata` parameter does not in any way control how the image data is stored in TIFF. In this case tifffile defaults to writing a RGB image with samples in separate planes. This default might actually change at some point. Better be explicit and define the `photometric` or `planarconfig` parameters.

**Comment by manthey** [comment]
@zjniu Your code snippet worked for me directly.

**Comment by cgohlke** [comment]
Re `2023_05_23_pw020_ctrl_well1.tif`: it appears the TIFF was originally created by tifffile with separate samples and then later rewritten by another software with interlaced samples, at which point the metadata in the ImageDescription tag got out of sync. The same would have happened with OME-TIFF or ImageJ format.

**Comment by zjniu** [comment]
@cgohlke Thanks for the insight. I'm not sure how that happened as that should have been a direct output by tifffile. Regardless, @manthey, I uploaded the file I created using the code snippet above and it now works.
