### ISSUE TITLE
Add different compositing options

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#504]
Should be added to Settings -> Viewer options.

**Comment by arjunrajlab** [comment]
I think we had these options in a very early version of the project, like near the beginning. It may be possible to find the options there.

**Comment by arjunrajlab** [comment]
Here's the commit where it was removed:

https://github.com/Kitware/UPennContrast/commit/c28d6e6a3ad31acf6e3a2a6a4347b87470f45693

@manthey needs to do a backend update to push out an overview panel that reflects the different composition mode, but I think that can be done independently of the UI and main viewer compositing change.

**Comment by manthey** [comment]
See also https://www.w3.org/TR/compositing-1/#advancedcompositing

**Comment by bruyeret** [comment]
See https://github.com/Kitware/UPennContrast/commit/c28d6e6a3ad31acf6e3a2a6a4347b87470f45693

**Comment by arjunrajlab** [comment]
I was looking at the various compositing options. Seems like the only ones that show any sort of normal looking image are "lighten" and "screen". Perhaps we can put those two at the top?

**Comment by bruyeret** [comment]
Some composition modes have a problem (the ones that work with a white background or the normal for example): images sent by girder have a black background
Can I instead query for an image with a transparent background? @manthey 
At the moment, the gradient is computed using the palette `[#000000, #{layer color}]` in the query but I didn't find a way to specify alpha in the palette
Here is a result using the css filter on each layer `invert(100%) hue-rotate(180deg)` in darken mode:
![image](https://github.com/Kitware/UPennContrast/assets/90781029/8f0ec786-4629-4e2f-a706-2f7c2051f5f0)

The equivalent in lighten mode with black background and no filter:
![image](https://github.com/Kitware/UPennContrast/assets/90781029/094a5638-0aa5-4674-a9fd-bdf80a755952)

Normal composition mode needs a transparent background and I don't think that there is a filter for that in css

**Comment by arjunrajlab** [comment]
@bruyeret I think it is pretty unlikely… I have not encountered such an image. But we could just put them in an "advanced modes" dropdown or something just in case.
