### ISSUE TITLE
Multi-source not parsing correctly

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#511]
In this folder, there are two .tiff files, green.tiff and phase.tiff:
https://www.dropbox.com/sh/dmdhb13sa6frzjj/AACeYQ3cUMLaqtJKQqVjNDdda?dl=0

Both have 10 frames in them, so 10 XY positions. However, if I try and upload both as a multi-source, it interprets it as two channels and 20 XY positions, which is incorrect:

<img width="1178" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/1f26b09d-d6cd-4a13-a849-ab8118d27fff">

**Comment by bruyeret** [comment]
This comes from what looks like a feature but I can't find a use case for it:
If we have 2 files with 10 frames each, the algorithm is doing as if we were choosing XY for both the filename variable and the file metadata
But we can't assign to XY the 10 frames per file AND the 2 files
Do you see a case where a file metadata dimension could be the same dimension as the files ?
If not, I will just remove this small part of the code

**Comment by arjunrajlab** [comment]
Oh weird. I'm not sure if I'm fully understanding, but I think the expected behavior here should be 10x2 (XYxC), not 20x2. I don't think the other scenario would show up often.

Perhaps it is there because if you uploaded multiple ND2 files that were e.g. 5x2 (XYxC), then maybe you want to conjoin them to be 10x2. But I wouldn't worry about that right now.

So I guess remove the code! :) 

Thanks!
