### ISSUE TITLE
If you upload a file while in a folder, the default location of that file should be in the folder.

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#517]

**Comment by bruyeret** [comment]
What does "in a folder" mean?
Do you mean when the user is in the home view, and the file manager is open?

**Comment by arjunrajlab** [comment]
Yes, sorry, exactly that: when in folder in the home view/file manager. I actually wonder if might be better to wait until we re-do the file ingestion UI to fix this issue.

**Comment by bruyeret** [comment]
Ok no problem, I am waiting for your approval before working on this issue
You can even put it back in the backlog if you prefer

**Comment by arjunrajlab** [comment]
I think whatever folder you are in here:
<img width="334" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/70ea93dd-5a78-4a17-b67b-606c3b7332cf">

Should go here:
<img width="413" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/6354ce7e-157f-43c7-a855-5db0c9eb01ff">

**Comment by arjunrajlab** [comment]
I think this is what should happen for comprehensive upload. We can decide about quick upload.
