### ISSUE TITLE
Color picker issues/bugs

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#520]
If the color picker is in light mode, white doesn't show up. I think having a small black circle around the color should solve the problem:

<img width="294" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/2a8512f2-752c-496a-99d7-9abf7ba7b48b">
<img width="290" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/a42ce440-d171-4193-828d-855dc2df6e9d">

The Hex code for the color is not editable. I suggest we just get rid of the hex code and just show the color itself.

The double arrow here is not particularly discoverable (I didn't know what it did until just now). I thought it was for adjusting the numbers because of the arrows, but was surprised to see I could do HSV or Hex there. Maybe we can replace with a hamburger or "…" button?

<img width="274" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/46b6d194-be26-4c36-91a4-e6ad6671df71">

Also, currently, if you go around in the color picker, there is no way to pick white, which is probably one of the most commonly used options:

<img width="290" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/782bfbfb-1acf-433d-9e0c-93e698fbadf8">

Is there a more appropriate color picker we can use?

**Comment by bruyeret** [comment]
I think that I managed to fix everything but the icon problem
It is a vuetify component so I have less control on these kind of things
I can change the css (add shadow or border, change background...) or remove it
What do you prefer ?
I can also set a default mode (rgb, hex or hsl)

**Comment by arjunrajlab** [comment]
Can we maybe just add a small black border? I think that would solve the issue. If that doesn't work easily, then we can just not worry about it.
Default mode of RGB is probably the most intuitive.
