### ISSUE TITLE
Delete connections tool works, but interface doesn't update

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#538]
If I make the following tool:

<img width="693" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/acef7118-d150-498d-b70e-db5e8e224302">

I can circle connections, but the interface doesn't update:
<img width="1404" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/37f424bc-1efa-44cf-b731-519ae5ceda41">

If I refresh, though, the connections were in fact deleted:
<img width="1408" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/5f6ad085-1f97-4361-bfb7-1c9f0d89381f">

**Comment by bruyeret** [comment]
I accidentally pushed a fix on master
Lucie has changed the settings of `master` to prevent this to happen again
The change only affects 2 lines, so you can maybe pull master and close the issue if it fixes the problem @arjunrajlab?

**Comment by arjunrajlab** [comment]
Just tested, it is fixed, thank you!
