### ISSUE TITLE
Unusably slow performance with a relatively small file set

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#548]
I have been trying to load the following relatively small dataset:

https://www.dropbox.com/sh/lkebqj224dwtauu/AAAzz9ZMQGKCBqNISxXbjaVsa?dl=0

The multi-file import works, but the file view is REALLY slow, even though this is a relatively small set of files. I think this would need to be fixed, since these file types are relatively common.

**Comment by arjunrajlab** [comment]
I also just tried transcoding to TIFF, and Girder just straight up crashed.

**Comment by arjunrajlab** [comment]
(Probably an memory issue, but still.)

**Comment by arjunrajlab** [comment]
When I used just 3 files and transcoded into TIFF, the image was very usable, so it seems that multi-file source is very poor performance without the transcoding.

**Comment by arjunrajlab** [comment]
@manthey How much memory is required for transcoding?

**Comment by arjunrajlab** [comment]
Update: transcoding and performance much better on Linux.

**Comment by manthey** [comment]
A quick look -- these are somewhat strangely written tiff files.  They have an lzw compressed image that is around 8k square, plus a 1x1 pixel image that is also lzw compressed.  Why do they have this extra 1x1 pixel image?

**Comment by arjunrajlab** [comment]
No clue, they are indeed quite weird. They come off of one of our imaging machines. I don't know what the 1x1 pixel image is about. But in testing with transcoding (on linux), it seems to be performant. The transcoding is definitely slow, but I guess that cannot be avoided.
