### ISSUE TITLE
Updated UI to Collection view

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#563]
I really like this updated UI for the Collection view:

<img width="895" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/1cd45d1e-2393-4117-b569-cf4c10bafa7b">

The most important part is the "Add dataset to current collection" button:
<img width="445" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/d4a265a9-dfec-4d27-867c-220183faf655">

This button here should say "Delete collection", but we have to figure out the logic of this option.

<img width="494" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/d5e77698-a729-437e-a3d4-bf1927962116">

The thing is that every dataset has to belong to a collection. So if you delete the collection, what happens? It's not bad per se, but if you have a dataset that has no collection, then it should create a new collection when you try and reopen it. I'm not sure if that's currently the case.

**Comment by bruyeret** [comment]
Also fixes the reviews from this PR: https://github.com/Kitware/UPennContrast/pull/598

**Comment by bruyeret** [comment]
In [this review](https://github.com/Kitware/UPennContrast/pull/598#issuecomment-1816468892)
What should happen if the user adds several datasets to the configuration

For [this review](https://github.com/Kitware/UPennContrast/pull/598#issuecomment-1816471019)
When an incompatible dataset is uploaded, what do you think if the upload modal closes and a new modal with a warning message saying `Incompatible dataset uploaded: the uploaded dataset is not compatible with the current configuration`?

**Comment by arjunrajlab** [comment]
@bruyeret Good points!
I think if someone adds multiple datasets to the configuration, then we should just pick the first of the new datasets in whatever order they go into the list with.

For the question about the modal for incompatible dataset… I like your approach! Yes, let's just make a modal like that. Thanks!
