### ISSUE TITLE
Help button on UI

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#566]
I like this little help button:

<img width="493" alt="image" src="https://github.com/Kitware/UPennContrast/assets/13998824/1c12505f-6128-4d79-ad32-838eae519a9d">

I think clicking it should bring up the HUD (equivalent to pressing tab). In the HUD, let's put a URL at the bottom of the HUD with a link to the full documentation.

**Comment by bruyeret** [comment]
I just need a link to the documentation
I remember that it was a git book but I can't find the link anymore
Maybe I could also add that link to the README
