### ISSUE TITLE
Zeiss file causes skyrocketing memory usage and crash, doesn't load

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#595]
Tried to upload this pretty small CZI (Zeiss) file. It got stuck after the upload and never stopped, and eventually used up all the RAM on my machine.

https://www.dropbox.com/scl/fi/uv4sc4zkj4xenr4k7dxsu/well3_raw_2.czi?rlkey=x8srk0vzdcmedov3rps8fva63&dl=0

It's a simple 4 color z stack.

**Comment by arjunrajlab** [comment]
This appears to be a Mac-specific issue.

**Comment by arjunrajlab** [comment]
Actually, the performance on this relatively small dataset seems very poor…

http://ec2-3-83-221-74.compute-1.amazonaws.com:8081/#/datasetView/654bf24e7854b6d57ff106e1/view?z=16

**Comment by arjunrajlab** [comment]
It appears to be a front end issue @bruyeret

**Comment by arjunrajlab** [comment]
@bruyeret an interesting data point: if you transcode to TIFF, you get the issue. If you do NOT transcode to TIFF, the issue is not there.

**Comment by bruyeret** [comment]
The performance issue comes from Vue's reactivity as said before
It occurs when calling `map.draw();` in `ImageViewer.vue` at line 966
The reason is that the geojs fetch queue is reactive and the update function is adding around 1000 elements in it
The complexity of doing so when the _queue attribute is reactive is quadratic
Commenting out `mapentry.params.layer.queue = [...mapentry.imageLayers[0].queue];` l.798 fixes the issue
I still have to investigate how to properly solve the issue tomorrow but maybe you have a clue @manthey ?

**Comment by arjunrajlab** [comment]
Interesting! Why does it only happen when converted to TIFF? Does that provide some clue?

**Comment by bruyeret** [comment]
I don't know how this is linked to converted TIFFs yet
Maybe the queue is bigger when using converted TIFFs
It doesn't seem to come from `queue` being reactive, as it is reactive even when commenting out the line
It is the assignation itself which causes issues
`mapentry.params` is built using [`pixelCoordinateParams`](https://opengeoscience.github.io/geojs/apidocs/geo.util.html#.pixelCoordinateParams)
Is it really necessary to do this assignation @manthey? What is its purpose?

**Comment by bruyeret** [comment]
I saw in an earlier commit this commit message, which could explain why :
> Used a shared tile queue across layers.
> 
> This should make the browser somewhat more responsive, as it will have
> fewer queued requests after panning or adjustments.
But I don't understand how this optimization is supposed to work

**Comment by manthey** [comment]
This shouldn't have anything to do with the reactivity.  Specifically, browsers will only allow (under HTTP 1.x) 6 concurrent requests at a time.  The tile layer on geojs will ask for five or six tiles at a time, holding off further requests until the tile is served.  This allows other web site navigation to occur promptly and makes it so if you pan or zoom before a tile is served it may skip asking for it.  Having a merged tile queue for multiple layers means that all of the layers together will only request 5 or 6 tiles at a time; having separate tile queues means each layer can ask for that many tiles.  You shouldn't see any change in cpu usage, just a different number of pending GET requests for tile images.

**Comment by bruyeret** [comment]
The flame graph [here](https://share.firefox.dev/47rbDqa) shows most of the time is spent in `dependArray` of Vue (the array being the queue). And removing the line `mapentry.params.layer.queue = mapentry.imageLayers[0].queue;` reliably fixes the issue. Maybe having the queue "owned" by two layers creates a reactivity issue.
My hypothesis is that both layers are editing the queue and reacting to the other layer's changes (and kind of playing ping pong), until the queue is empty (all requests are given to the browser). But I don't know what the change is.

**Comment by manthey** [comment]
I don't think we want vue to have the queue in its reactivity layer at all -- is there a way to exclude it?

**Comment by bruyeret** [comment]
David may have found a solution.
TODO: test this to remove reactivity on the queue:
```js
mapentry.params = markRaw(params);
```

**Comment by manthey** [comment]
I found this diff (on current master) seems to resolve this issue:
```
--- a/src/components/ImageViewer.vue
+++ b/src/components/ImageViewer.vue
@@ -125,6 +125,7 @@ import annotationStore from "@/store/annotation";
 import store from "@/store";
 import girderResources from "@/store/girderResources";
 import geojs from "geojs";
+import { markRaw } from "vue";

 import {
   IGeoJSMap,
@@ -662,8 +663,8 @@ export default class ImageViewer extends Vue {
       map.geoOn(geojs.event.pan, () => this._handlePan(mllidx));
       mapentry = {
         map: map,
-        imageLayers: [],
-        params: params,
+        imageLayers: markRaw([]),
+        params: markRaw(params),
         baseLayerIndex: mllidx ? undefined : 0
       };
       Vue.set(this.maps, mllidx, mapentry);
@@ -694,7 +695,7 @@ export default class ImageViewer extends Vue {
       mapentry.textLayer.node().css({ "mix-blend-mode": "unset" });
     } else {
       mapentry = this.maps[mllidx];
-      mapentry.params = params;
+      mapentry.params = markRaw(params);
       map = mapentry.map;
       const adjustLayers =
         Math.abs(map.maxBounds(undefined, null).right - mapWidth) >= 0.5 ||
```

**Comment by arjunrajlab** [comment]
I think the above is because we recently made a change where it looks at the first couple files (?) and then if consistent in shape, does the rest. I'm not sure why getting rid of reactivity for this made it work better, but overall, I think this variable assignment screen is also working better in terms of responsiveness, so that is good.

**Comment by arjunrajlab** [comment]
I made a branch for it: `fix-reactivity-bug`
