### ISSUE TITLE
Snapshots are not aware of multiple files within a collection

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#623]
If you take a snapshot in dataset1 from a collection, then move to a different dataset (dataset2) and select the snapshot from dataset1, the snapshot navigates to the location of the snapshot in dataset2. It should navigate back to dataset1. I am guessing we just forgot to consider this possibility when we moved from single datasets to collections of datasets. We should probably also include an extra field in the snapshot browser list that shows the snapshot dataset so that people know which dataset the snapshot is from.

**Comment by bruyeret** [comment]
When adding a dataset ID attribute to the snapshot, I found out that the snapshot saves a format (jpg, tiff...)
I wonder if this is relevant, as when we want to download all the snapshots, we want to do it using the format that the user has selected in the UI
Do you confirm that I can remove the format from the snapshot?

**Comment by arjunrajlab** [comment]
Oh, I see, yes, we can just remove the format from the snapshot structure and instead just do whatever the user has chosen in the UI.
