### ISSUE TITLE
Remaining SAM interface items

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#646]
Task list for remaining items for SAM implementation in NimbusImage:

- [ ] **Enable "live preview".** It would be great to show a live preview of the mask that would be generated if the user clicks. It should just run SAM on the current point as the prompt. It doesn't need to process the mask at all—if it generates a complex mask, that is fine, the user will know that it may get simplified upon committing it to an annotation.
- [ ] **Progress bar for the encoder.** The encoder takes some time to compute, especially on older computers. It would be good to show some indicator on the screen or on the tool itself to show that it is doing the encoding. Perhaps also could be merged with this? https://github.com/Kitware/UPennContrast/issues/549
- [ ] **Interface for the tool.** I think there should be a toggle between "turbo mode" and "complex prompt mode". In turbo mode, you can shift click or shift drag, and it will automatically commit the annotation upon click/end of drag. That way, if someone just wants to quickly click on a bunch of objects, they can do so. In turbo mode, if you make an annotation, it gives you an "Oops, cancel!" link/button in the bottom left that allows you to undo the latest annotation quickly (lasts for 1 second). In complex prompt mode, it can allow for more complex prompts with multiple foreground and background prompt points/rectangles. In that mode, the existing buttons should be sufficient.
- [ ] **Simplify the polygon.** Give an optional "smoothing parameter" (default 1.5) to send to the algorithm to smooth out the resulting polygon so that it doesn't have quite so many points.

**Comment by bruyeret** [comment]
- Ctrl-Z to cancel last annotation
- Help alert when opening SAM tool (shift click / drag)
