### ISSUE TITLE
Multi-source datasets are not uploading properly anymore

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#667]
@manthey It seems that datasets that used to load okay recently stopped uploading. Here are a couple examples:

https://www.dropbox.com/scl/fo/v3vc5bx5say3oq9wgox35/AFP0BimbrIm8ir8TfgJcrYk?rlkey=a9vt9red1q50lxglkh79p73v7&dl=0

If you upload all the files, it won't even accept them all. I've tried subsets of even 3-4 images, and then the VIPS TIFF transcode hangs. Not sure what happened, these files used to ingest just fine.

**Comment by manthey** [comment]
This should improve the situation: https://github.com/girder/large_image/pull/1515

Something about tifffile is much slower than it used to be.  The mentioned PR works around it.
