### ISSUE TITLE
getAnnotationsByDatasetId is slow regardless of the number of annotations

### ISSUE THREAD

**Issue by zjniu** [Kitware/UPennContrast#672]
Running the following line of code
`annotationList = annotationClient.getAnnotationsByDatasetId(datasetId)`
is very slow. Regardless of the number of total annotations, it takes around 20 seconds to grab the list of annotations. Even if the dataset has no annotations, it takes around the same amount of time to grab the list.

**Comment by arjunrajlab** [comment]
I will also say that I have noticed this slowdown and it is very recent, like, within the last week or two at most.

**Comment by arjunrajlab** [comment]
Resolved by https://github.com/Kitware/UPennContrast/pull/677
