### ISSUE TITLE
Request: Default Brightfield Channel to greyscale

### ISSUE THREAD

**Issue by pburnham50** [Kitware/UPennContrast#68]

**Comment by manthey** [comment]
@pburnham50 Besides having Brightfield always map to greyscale, do you want any other channels to have consistent mapping?  Currently, we map them to red, green, blue, etc. in the order they are listed in the file(s).

**Comment by pburnham50** [comment]
Could you default the following:
- YFP/GFP go to green.
- DAPI to blue
- A594 to red
- Cy3 to orange
