### ISSUE TITLE
In tool edit, changing tag in one dataset does not propagate to other datasets in the collection

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#700]
If you edit an existing tool, if you change the tags associated, it only seems to change for the current dataset and does not change for other datasets in the collection.

**Comment by bruyeret** [comment]
I tried to reproduce but didn't manage
Maybe the user opened the datasets of the same collection in two tabs and updated the tool in one of the tabs, expecting the change to sync immediately on the other tab
This is currently not supported and the user will have to manually refresh the tab

**Comment by arjunrajlab** [comment]
I will check with the user to see about reproducing the issue.

**Comment by arjunrajlab** [comment]
Seems to not be reproducible on our end.
