### ISSUE TITLE
I'm wondering: does the JSON import code use the new multiple property value endpoint?

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#752]
I'm not sure I fully understand this code, but it seems like it uploads the property values one at a time? That would be very slow, I think.

https://github.com/Kitware/UPennContrast/blob/f7408f7811d437464d4cbbdbe0b73f2ab3b4df62/src/components/AnnotationBrowser/AnnotationImport.vue#L312C13-L317C1

**Comment by bruyeret** [comment]
Yes it doesn't use the new endpoint, I am fixing it 👍
