### ISSUE TITLE
annotation buttons run "underneath" image in viewer.

### ISSUE THREAD

**Issue by pburnham50** [Kitware/UPennContrast#77]
<img width="1813" alt="Screen Shot 2020-10-22 at 10 47 49 AM" src="https://user-images.githubusercontent.com/11461194/96893431-af8f1700-1458-11eb-9c70-a4bbcc017ffd.png">

when adding in new buttons to the annotation, the buttons run underneath the image. 

is there a way we can give them a right margin to force them downward?

**Comment by manthey** [comment]
This is no longer relevant with other recent changes.
