### ISSUE TITLE
"Snapshot -> Download screenshot of current viewport" not working

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#773]
If you click this button, nothing happens. The console shows an error of "Failed to render html to image".

**Comment by arjunrajlab** [comment]
Update @bruyeret: I found that it works fine with my localhost install. The problem only shows up on nimbusimage.org and nimbusimage.com. Perhaps it's some CORS issue? Not sure.

**Comment by manthey** [comment]
This is fixed by https://github.com/OpenGeoscience/geojs/pull/1334
