### ISSUE TITLE
color mapping on client side

### ISSUE THREAD

**Issue by sgratzl** [Kitware/UPennContrast#8]
atm the color mapping is done on the server side using the `style` option. With rapid changes in the histogram this becomes quite slow. 

One possibility is to transfer the TIFF to the client and then do the color mapping there directly (e.g. in WebGL. see also https://geotiffjs.github.io. In combination with regular OpenGL Blending, one can do the merging of multiple layers

**Comment by manthey** [comment]
In the current implementation of style in large_image, the change in style reopens the tile source file.  This can be modified to cache everything except the style application.  If this is fast enough, it might be preferred to having more code in the client.  If we are using client code, we'll need to ensure that the client correctly handles 16-bit per channel (and possibly other formats).

**Comment by manthey** [comment]
With the histogram preview, this is no longer a significant issue.
