### ISSUE TITLE
Snapshot tools

### ISSUE THREAD

**Issue by manthey** [Kitware/UPennContrast#82]
This issue is primarily for feedback before the expanded snapshot dialog lands.  The initial mockup looks like this:
![image](https://user-images.githubusercontent.com/8781639/111843477-aacf7180-88d7-11eb-93a1-e8a6ff946058.png)
where, when a snapshot is loaded, a url will appear below the name of the current snapshot that can be pasted into a browser to get back to that view.

**Comment by arjunrajlab** [comment]
So here is the drawn out version of what I had initially mocked up. Rather than have a dropdown to browse snapshots, I think it would be better to have a list view. That will also facilitate filtering by tags, which will be a very important feature to have.

<img width="687" alt="Untitled" src="https://user-images.githubusercontent.com/13998824/112476269-19815480-8d48-11eb-8385-3046767c101d.png">

**Comment by manthey** [comment]
We'll definitely add support for tags.

I was thinking that snapshots would be saved with specific configurations.  Loading a snapshot would load that specific configuration.  As such, the dialog I showed above would be on a specific configuration.  In addition to the controls shown, there could be a control for adding tags when creating a snapshot and for filtering snapshots by tags to reduce the listed snapshots.  

I'm not sure how many snapshots would be likely on one configuration.  We currently allow multiple configurations per source file set, but snapshots will largely make those multiple configurations unneeded.

I think there would ultimately be another dialog or page that would let you search snapshots across multiple configurations (and, hence, source images).  Here the search might be more general: tags, descriptions, name of snapshot (and probably name and description of source file set).

**Comment by arjunrajlab** [comment]
Excellent question: I was thinking Snapshots would be associated with a particular dataset. I had not considered it, but yes, I think that each Snapshot for a particular dataset should have an associated configuration that is "compatible" with the Snapshot (there can be multiple configurations used for a particular dataset). I think the Snapshot browser could have a field in the list that shows what configuration the Snapshot used. Then, if you switch to a Snapshot for a different configuration, it would switch the current configuration. Most of the time, I would imagine there is probably going to be just 1 or maybe 2 configurations used per dataset, but in principle it could be possible to have Snapshots with different configurations, and I would imagine users would want to browse them all.

**Comment by arjunrajlab** [comment]
Updated previous comment to reflect "View" terminology :). Also, key priority items are:
1. Creating "bounding box" functionality, which is draggable/resizeable and also precisely editable by changing text fields for "top" "left" "height" "width".
2. Exposing TIFF as an export format.
