### ISSUE TITLE
Color-picker on brightfield image is diabled/not working (works sometimes, but not others).

### ISSUE THREAD

**Issue by pburnham50** [Kitware/UPennContrast#84]
<img width="427" alt="Screen Shot 2021-05-14 at 8 47 32 AM" src="https://user-images.githubusercontent.com/11461194/118272737-0dd12500-b491-11eb-8596-33a5d3024758.png">

**Comment by arjunrajlab** [comment]
I have reproduced this issue. Maybe if a channel is assigned to FFFFFF (i.e., white), then moving the slider just doesn't do anything because everything is already saturated? Not sure.
