### ISSUE TITLE
Make color-picker text have better contrast against background.

### ISSUE THREAD

**Issue by pburnham50** [Kitware/UPennContrast#88]
The text in the color picker is black even in dark mode, making the text very hard to read.

**Comment by arjunrajlab** [comment]
I'm still seeing this issue…
![image](https://user-images.githubusercontent.com/13998824/126043231-a3be41e6-3274-4fe1-84bb-fce816386ec7.png)

**Comment by boucaud** [comment]
Hello @arjunrajlab ! Can you try running `npm install`, then testing again ?

**Comment by arjunrajlab** [comment]
That worked, thanks!!
