### ISSUE TITLE
Label slider bounds

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#90]
Sliders start from 0 (should start from 1), should also display the upper bound somewhere on the UI. It is very helpful for users, because it helps them orient themselves in their data. If we can show tick marks, great, but not necessary yet.

**Comment by manthey** [comment]
Currently the upper bound is displayed as a tooltip.

**Comment by arjunrajlab** [comment]
I think having the upper bound as a number directly and persistently on the UI would probably be better for the user.
