### ISSUE TITLE
Major Task - Snapshot 

### ISSUE THREAD

**Issue by pburnham50** [Kitware/UPennContrast#96]
A Snapshot is an object that identifies a particular subset of an image along with contrast and image overlay settings. Information would include:
- DatasetID
- Description/Name
- An x-y “frame” (i.e., a rectangle containing the image)
- Z (merged or specific Z)
- Time (merged or specific)
- Channels that are active, along with color and contrast for each channel
- Image merge settings (if any; I think this was removed in latest UI)
- Tags (serves as folder to organize Snapshots; can go across datasets)
- Date and time created
- Date and time last modified
- Show scale bar (flag)
- Configuration (the configuration used for the Snapshot)

**Comment by manthey** [comment]
This was added in #107.
